### PR TITLE
remove leading underscore from lock_counter member

### PR DESCRIPTION
**Pull request by decrispell**
I haven't yet figured out why this change is needed for me - Perhaps the API of the `filelock` library changed recently?  I have `filelock` version 3.12.0,  Python 3.10.11

### CODE REVIEW

**Comment by decrispell** [comment]
https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.lock_counter

**Comment by scott-vsi** [comment]
Hmm, ya

https://github.com/tox-dev/py-filelock/commit/b4713c946cf8bcd65276bffbccef8f269d504dbd

The bigger question is why do you have v3.12.0. The Pipfile.lock says 3.10.2

**Comment by decrispell** [comment]
My project uses terra as a submodule/editable dependency and has its own Pipfile.lock, which does say 3.12.0.  If you wanted to ensure an older version of filelock is installed you probably need to specify something in the requirements.

**Comment by scott-vsi** [comment]
Ya. I guess we should set a version limit on filelock in the setup.py file

**Comment by decrispell** [comment]
Closing this PR because it would require updating terra's Pipfile, Pipfile.lock, which is not desirable.  Instead, users of terra should make sure that their version of lockfile is < 3.12

**Pull request closed without merging**
